name: CI

on: [push, pull_request]

# trigger action: this will be run by Github Actions

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   # get repo code
  
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3-setuptools
        sudo apt install pipx
        pipx install norminette
        pipx ensurepath
        sudo apt-get install gcc make xorg libxext-dev libbsd-dev

    - name: Compile
      run: make

    - name: Run program
      run: ./cub3d test_map.ber   # runs the compiled binary

    - name: Run norminette
      run: norminette src/
